server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adeshmahi18/configFiles
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true