spring:
  application:
    name: "EMPLOYEE"
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

resilience:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
server:
  port: 8081